name: Run Selenium Script

on:
  schedule:
    # 20:30 UTC = 2:00 AM IST
    - cron: "30 20 * * *"
  workflow_dispatch:   # also allow manual run from GitHub Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Chrome & Chromedriver
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver
        which chromium-browser
        which chromedriver

    - name: Run Selenium script
      run: |
        python main.py
